name: Attach Released Assets

on:
  release:
    types:
      - created

jobs:    
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Initialize submodules
        run: git submodule update --init --recursive

      - uses: papeloto/action-zip@v1
        with:
          files: analyzers/ Help/ spec/ languages/ misc/ ecl/ python/
          recursive: false
          dest: visualtext.zip
          
      - uses: actions/upload-artifact@v4
        with:
          name: visualtext
          path: ${{ github.workspace }}/visualtext.zip
          
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: visualtext.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
